# Generated by Django 2.2.4 on 2019-11-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('Wedding', 'Wedding'), ('Naming Ceremony', 'Naming Ceremony'), ('Birthday', 'Birthday'), ('Graduation', 'Graduation'), ('Hang-out', 'Hang-out'), ('Others', 'Others')], max_length=50)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('expected_number', models.IntegerField()),
                ('budget_range', models.IntegerField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
